server:
  port: 8081

spring:
  application:
    name: iam-springboot-backend
  datasource:
    url: jdbc:mysql://localhost:3306/iamdb
    username: root
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # 0IDC Clients (fill in your credentials)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: openid,profile,email
            redirect-uri:
          github:
            client-id:
            client-secret:
            scope: read:user,user:email
            redirect-uri:
          auth0:
            client-id:
            client-secret:
            scope: openid,profile,email
            redirect-uri:

        provider:
          auth0:
            issuer-uri:
security:
  jwt:
    issuer: ${JWT_SECRET}
    secret: cross-platform-iam
    expires-min: 60m

tenant:
  header: "X-Tenant-ID"


